### ISSUE TITLE
No new FCS files: "replacement has 0 rows, data has 71"

### ISSUE THREAD

**Issue by chaja123** [dtelad11/cytutils#14]
Thank you for your code. 
When I run it, it smoothly creates the channel_rename.csv, but then when I change one of the values for new_name, save it, and run the line again, I get the following error: 

Importing channel_rename.csv and exporting new FCS files
Error in `$<-.data.frame`(`*tmp*`, "name", value = character(0)) : 
  replacement has 0 rows, data has 71

How to manage this error? I am using R studio v.4.2.1.

**Comment by chaja123** [comment]
Apparently, by opening and renaming it in Excel (the default app for opening CSV in windows), even if you then again save it as a CSV, it changes the conformation of the file in such a way that it becomes useless for cytutils. Changing the names in the notepad does work.

**Comment by SamGG** [comment]
Right solution. Thanks for sharing your feedback.
A CSV file is mainly a text file. But CSV separator is ";" instead of "," in certain countries. Nowadays, I don't use CSV file anymore having switched to XLXS that don't care about the field separator whatever the country. I think XLSX files are also correctly handled by alternatives to M$ Excel. Would be great to allow XLSX file in addition to CSV file.
